services:
  homer-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homer-manager
    # ports:
    #   - "8080:8080"
    volumes:
      - ./assets:/app/assets
    environment:
      - NODE_ENV=production
    restart: unless-stopped