title: Default Title
subtitle: Welcome to your Homer Dashboard
logo: logo.png
header: false
footer: false
stylesheet:
  - assets/custom.css
columns: "2"
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: rgba(255, 245, 242, 0.8)
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: ../assets/wallpaper-light.jpeg
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: rgba(24, 28, 58, 0.8)
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: ../assets/wallpaper.jpeg
services:
  - name: Apps
    icon: fas fa-code
    items:
      - name: Immich
        logo: assets/tools/immich.png
        tag: Photos
        url: https://immich.app/
        target: _blank
        tagstyle: is-info
